language: python

addons:
  apt:
    packages:
      - openjdk-8-jre  # install Java8 as required by html5validator (vnu.jar)

#services:

#env:
# global:
# These global enviromental variables are required and defined @ travis-ci.org / repository / settings / Environment Variables
#  - AWS_REGION=ue-west-1
#  - AWS_S3_BUCKET=myweb.mydomain.com   ## !! without s:// as with aws s3 comand 
#  - AWS_S3_ACCESS_KEY=
#  - AWS_S3_SECRET_KEY=

#cache:
#before_install:

install:
 - pip install html5validator

#before_script:

script:
  - html5validator --root webroot/

#before_deploy:

deploy:
  provider: s3
  region: ${AWS_REGION}
  access_key_id: ${AWS_S3_ACCESS_KEY}
  secret_access_key: ${AWS_S3_SECRET_KEY}
  bucket: ${AWS_S3_BUCKET}
#  skip_cleanup: false
  acl: public_read
  local_dir: webroot
#  upload-dir: travis-builds
  
  
#notifications:
