language: python

addons:
  apt:
    packages:
      - openjdk-8-jre  # install Java8 as required by html5validator (vnu.jar)

#services:
#env:
#cache:
#before_install:

install:
 - pip install html5validator

#before_script:

script:
  - html5validator --root webroot/

#before_deploy:

deploy:
  provider: s3
  region: ${AWS_REGION}
  access_key_id: ${AWS_S3_ACCESS_KEY}
  secret_access_key: ${AWS_S3_SECRET_KEY}
  bucket: ${AWS_S3_BUCKET}
#  skip_cleanup: false
  acl: public_read
  local_dir: webroot
#  upload-dir: travis-builds
  
  
#notifications: