language: python

#addons:
#services:
#env:
#cache:
#before_install:
#install:
#before_script:

script:
  # faking unit testing here ...
  - echo "All tests OK"

#before_deploy:

deploy:
  provider: s3
  region: AWS_REGION
  access_key_id: AWS_S3_ACCESS_KEY
  secret_access_key: AWS_S3_SECRET_KEY
  bucket: AWS_S3_BUCKET
#  skip_cleanup: false
  acl: public_read
  local_dir: webroot
#  upload-dir: travis-builds
  
  
#notifications: