version: 2

machine:
  timezone: Europe/Dublin
  environment:
    AWS_REGION: eu-west-1
    AWS_S3_BUCKET: test.jannavratil.com
#  - AWS_S3_ACCESS_KEY=
#  - AWS_S3_SECRET_KEY=	

jobs:
  build:
    docker:
#      - image: debian:stretch
      - image circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Install HTML5validator
          command: pip install html5validator
#          command: wget https://github.com/yui/yuicompressor/releases/download/v2.4.8/yuicompressor-2.4.8.jar
      - run:
          name: Test HTML5 syntax
          command: html5validator --root webroot/
#          command: java -jar yuicompressor-2.4.8.jar webroot/css/*.css -o '.css$:-min.css'