version: 2

machine:
  timezone: Europe/Dublin
  environment:
    AWS_REGION: eu-west-1
    AWS_S3_BUCKET: test.jannavratil.com
#  - AWS_S3_ACCESS_KEY=
#  - AWS_S3_SECRET_KEY=	

jobs:
  build:
    docker:
      - image: debian:stretch
#      - image circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
