version: 2

machine:
  timezone: Europe/Dublin

jobs:
  build:
    docker:
      - image: "circleci/python:3.6-stretch-browsers"
    environment:
#      AWS_REGION: eu-west-1
      AWS_S3_BUCKET: test.jannavratil.com
#  - AWS_S3_ACCESS_KEY=
#  - AWS_S3_SECRET_KEY=	
    steps:
      - checkout
      - run:
          name: Install AWS tools
          command: sudo pip install awscli
      - run:
          name: Install HTML5Validator
          command: pip install --user html5validator
      - run:
          name: TEST HTML syntax
          command: /home/circleci/.local/bin/html5validator --root webroot/
      - run:
          name: Deployment to AWS
          command: aws s3 sync webroot s3://$AWS_S3_BUCKET --acl public-read --delete
