version: 2

machine:
  timezone: Europe/Dublin

jobs:
  build:
    docker:
#      - image: debian:stretch
      - image: "circleci/python:3.6.1"
    environment:
      AWS_REGION: eu-west-1
      AWS_S3_BUCKET: test.jannavratil.com
#  - AWS_S3_ACCESS_KEY=
#  - AWS_S3_SECRET_KEY=	
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo $AWS_REGION / ${AWS_S3_ACCESS_KEY}
      - run:
          name: Install HTML5Validator
          command: pip install html5validator
      - run:
          name: Print the Current Time
          command: date
#  test:
#    steps:
#      - run:
#          name: HTML syntaxt test
#          command: html5validator --root webroot/
